# n8n-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/n8n  # Local path on your node (change as needed)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
